fix: update naming from era_test_node to anvil-zksync
matter-labs/hardhat-zksync pull request #1567
Opened 2024-12-04 14:37 UTC by dutterbutter

# What :computer: 
* First thing updated with this PR
* Second thing updated with this PR
* Third thing updated with this PR

# Why :hand:
* Reason why first thing was added to PR
* Reason why second thing was added to PR
* Reason why third thing was added to PR

# Evidence :camera:
Include screenshots, screen recordings, or `console` output here demonstrating that your changes work as intended

# Notes :memo:
* Any notes/thoughts that the reviewers should know prior to reviewing the code?

2024-12-04 16:23 UTC, Romsters commented on packages/hardhat-zksync-node/src/constants.ts
> +export const ZKSYNC_ERA_TEST_NODE_NETWORK_NAME = 'anvil-zksync';
Maybe use `AnvilZKsync` for consistency?

2024-12-04 16:25 UTC, Romsters commented on packages/hardhat-zksync-upgradable/src/core/provider.ts
> +    260: 'ZKsync-anvil-zksync',
Maybe just `ZKsync-anvil` so zksync doesn't repeat twice?

2024-12-04 16:25 UTC, Romsters commented on packages/hardhat-zksync/README.md
> +| hardhat-zksync-node           | Convenient plugin to run the ZKsync anvil-zksync locally.                                                                        |
```suggestion
| hardhat-zksync-node           | Convenient plugin to run anvil-zksync locally.                                                                        |
```

2024-12-05 06:42 UTC, Romsters approved these changes

2024-12-05 06:43 UTC, Romsters requested changes
fix e2e please

2024-12-05 10:13 UTC, kiriyaga-txfusion commented
> fix e2e please

Redirecting the era-test-node repository to anvil-zksync will break all older plugins, as the redirection was designed to reduce GitHub API usage and prevent users from hitting API rate limits. This issue is evident in failing e2e tests, which rely on older plugin versions.

2024-12-05 10:17 UTC, kiriyaga-txfusion approved these changes

2024-12-10 13:35 UTC, Romsters approved these changes

2024-12-10 13:35 UTC, merged