Add legacyAssembly in outputSelection
matter-labs/hardhat-zksync pull request #378
Opened 2023-09-01 11:12 UTC by qiaoxrcn

2023-09-04 13:38 UTC, idea404 requested changes
We can not accept changing the evm.legacyAssembly in the output and compilation of the same code is performed multiple times, id vouch for closing this PR

2023-09-07 01:01 UTC, qiaoxrcn commented
> We can not accept changing the evm.legacyAssembly in the output and compilation of the same code is performed multiple times, id vouch for closing this PR

I'm trying to obtain the "evm.legacyAssembly" field. I'm using --force-evmla when running zksolc and adding evm.legacyAssembly to outputSelection, but it's not working. 

```
~/Library/Caches/hardhat-nodejs/compilers-v2/zksolc/zksolc-v1.3.14 --standard-json --system-mode --force-evmla --solc ~/Library/Caches/hardhat-nodejs/compilers-v2/macosx-amd64/solc-macosx-amd64-v0.8.17+commit.8df45f5f
{
  "language": "Solidity",
  "sources": {
    "contracts/Constant.sol": {
      "content": "// SPDX-License-Identifier: MIT\n\npragma solidity ^0.8.0;\npragma abicoder v2;\n\ncontract Constant {\n    uint c = 42;\n    constructor() {}\n\n    function getValue() public view returns (uint) {\n        return c;\n    }\n}\n \n"
    }
  },
  "settings": {
    "optimizer": {
      "enabled": true,
      "mode": "3"
    },
    "outputSelection": {
      "*": {
        "*": [
          "abi",
          "evm.methodIdentifiers",
          "metadata",
          "evm.legacyAssembly"
        ],
        "": [
          "ast"
        ]
      }
    },
    "libraries": {}
  }
}
{"contracts":{"contracts/Constant.sol":{"Constant":{"abi":[{"inputs":[],"stateMutability":"nonpayable","type":"constructor"},{"inputs":[],"name":"getValue","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"}],"metadata":{"optimizer_settings":"M3B3","solc_metadata":"{\"compiler\":{\"version\":\"0.8.17+commit.8df45f5f\"},\"language\":\"Solidity\",\"output\":{\"abi\":[{\"inputs\":[],\"stateMutability\":\"nonpayable\",\"type\":\"constructor\"},{\"inputs\":[],\"name\":\"getValue\",\"outputs\":[{\"internalType\":\"uint256\",\"name\":\"\",\"type\":\"uint256\"}],\"stateMutability\":\"view\",\"type\":\"function\"}],\"devdoc\":{\"kind\":\"dev\",\"methods\":{},\"version\":1},\"userdoc\":{\"kind\":\"user\",\"methods\":{},\"version\":1}},\"settings\":{\"compilationTarget\":{\"contracts/Constant.sol\":\"Constant\"},\"evmVersion\":\"london\",\"libraries\":{},\"metadata\":{\"bytecodeHash\":\"ipfs\"},\"optimizer\":{\"details\":{\"constantOptimizer\":false,\"cse\":true,\"deduplicate\":true,\"inliner\":true,\"jumpdestRemover\":true,\"orderLiterals\":true,\"peephole\":true,\"yul\":true,\"yulDetails\":{\"optimizerSteps\":\"dhfoDgvulfnTUtnIf[xa[r]EscLMcCTUtTOntnfDIulLculVcul [j]Tpeulxa[rul]xa[r]cLgvifCTUca[r]LSsTFOtfDnca[r]Iulc]jmul[jul] VcTOcul jmul\",\"stackAllocation\":true}},\"runs\":200},\"remappings\":[]},\"sources\":{\"contracts/Constant.sol\":{\"keccak256\":\"0x0fb1fe92951d79acb642a4f205563149154ab94d3b34c07a03f86d1c23d9b742\",\"license\":\"MIT\",\"urls\":[\"bzz-raw://3096b4efda2fe2a242c0f6d7ca0155e52aca6ff82839b5ddddf485fd7cf7c815\",\"dweb:/ipfs/QmagNnNh7x7LpfnxsiR7Lp175GPxkqEwu8hcGS54u2eqgH\"]}},\"version\":1}","zk_version":"1.3.14"},"evm":{"legacyAssembly":null,"assembly":"\t.text\n\t.file\t\"Constant.sol:Constant\"\n\t.globl\t__entry\n__entry:\n.func_begin0:\n\tptr.add\tr1, r0, stack[@ptr_calldata]\n\tshr.s\t96, r1, r1\n\tand\t@CPI0_0[0], r1, stack[@calldatasize]\n\tadd\t128, r0, r1\n\tst.1\t64, r1\n\tand!\t1, r2, r1\n\tjump.ne\t@.BB0_1\n\tcontext.get_context_u128\tr1\n\tsub!\tr1, r0, r1\n\tjump.ne\t@.BB0_3\n\tadd\tstack[@calldatasize], r0, r1\n\tsub.s!\t4, r1, r1\n\tjump.lt\t@.BB0_3\n\tptr.add\tstack[@ptr_calldata], r0, r1\n\tld\tr1, r1\n\tand\t@CPI0_2[0], r1, r1\n\tsub.s!\t@CPI0_3[0], r1, r1\n\tjump.ne\t@.BB0_3\n\tld.1\t64, r1\n\tsload\tr0, r2\n\tst.1\tr1, r2\n\tld.1\t64, r2\n\tsub\tr1, r2, r1\n\tadd\t32, r1, r1\n\tadd\t@CPI0_0[0], r0, r3\n\tsub.s!\t@CPI0_0[0], r1, r4\n\tadd.ge\tr3, r0, r1\n\tsub.s!\t@CPI0_0[0], r2, r4\n\tadd.ge\tr3, r0, r2\n\tshl.s\t64, r2, r2\n\tshl.s\t96, r1, r1\n\tor\tr1, r2, r1\n\tret.ok.to_label\tr1, @DEFAULT_FAR_RETURN\n.BB0_1:\n\tadd\t42, r0, r1\n\tsstore\tr0, r1\n\tcontext.get_context_u128\tr1\n\tsub!\tr1, r0, r1\n\tjump.ne\t@.BB0_3\n\tadd\t32, r0, r1\n\tst.2\t256, r1\n\tst.2\t288, r0\n\tadd\t@CPI0_1[0], r0, r1\n\tret.ok.to_label\tr1, @DEFAULT_FAR_RETURN\n.BB0_3:\n\tadd\tr0, r0, r1\n\tret.revert.to_label\tr1, @DEFAULT_FAR_REVERT\n.func_end0:\n\n\t.data\n\t.p2align\t5\ncalldatasize:\n\t.cell 0\n\n\t.p2align\t5\nptr_calldata:\n.cell\t0\n\n\t.note.GNU-stack\n\t.rodata\nCPI0_0:\n\t.cell 4294967295\nCPI0_1:\n\t.cell 53919893334301279589334030174039261352344891250716429051063678533632\nCPI0_2:\n\t.cell -26959946667150639794667015087019630673637144422540572481103610249216\nCPI0_3:\n\t.cell 14739606449177185611418819947874415371788578917829407236296623151976256897024\n","bytecode":{"object":"0002000000000002000100000001035500000060011002700000000d0010019d0000008001000039000000400010043f0000000101200190000000220000c13d0000000001000416000000000101004b0000002c0000c13d0000000001000031000000040110008c0000002c0000413d0000000101000367000000000101043b0000000f01100197000000100110009c0000002c0000c13d000000400100043d000000000200041a0000000000210435000000400200043d000000000121004900000020011000390000000d030000410000000d0410009c00000000010380190000000d0420009c000000000203801900000040022002100000006001100210000000000121019f0000002f0001042e0000002a01000039000000000010041b0000000001000416000000000101004b0000002c0000c13d0000002001000039000001000010044300000120000004430000000e010000410000002f0001042e000000000100001900000030000104300000002e000004320000002f0001042e000000300001043000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ffffffff0000000200000000000000000000000000000040000001000000000000000000ffffffff000000000000000000000000000000000000000000000000000000002096525500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000063f94188a4f3da3aabbf41869dfa14be16666c07acc1c4662ef832e919c5445e"},"methodIdentifiers":{"getValue()":"20965255"}},"hash":"01000013967b6a612e1074f6592881b2385cfb894b6a336cb6a284d2542bc6de","factoryDependencies":{}}}},"sources":{"contracts/Constant.sol":{"id":0,"ast":{"absolutePath":"contracts/Constant.sol","exportedSymbols":{"Constant":[18]},"id":19,"license":"MIT","nodeType":"SourceUnit","nodes":[{"id":1,"literals":["solidity","^","0.8",".0"],"nodeType":"PragmaDirective","src":"33:23:0"},{"id":2,"literals":["abicoder","v2"],"nodeType":"PragmaDirective","src":"57:19:0"},{"abstract":false,"baseContracts":[],"canonicalName":"Constant","contractDependencies":[],"contractKind":"contract","fullyImplemented":true,"id":18,"linearizedBaseContracts":[18],"name":"Constant","nameLocation":"87:8:0","nodeType":"ContractDefinition","nodes":[{"constant":false,"id":5,"mutability":"mutable","name":"c","nameLocation":"107:1:0","nodeType":"VariableDeclaration","scope":18,"src":"102:11:0","stateVariable":true,"storageLocation":"default","typeDescriptions":{"typeIdentifier":"t_uint256","typeString":"uint256"},"typeName":{"id":3,"name":"uint","nodeType":"ElementaryTypeName","src":"102:4:0","typeDescriptions":{"typeIdentifier":"t_uint256","typeString":"uint256"}},"value":{"hexValue":"3432","id":4,"isConstant":false,"isLValue":false,"isPure":true,"kind":"number","lValueRequested":false,"nodeType":"Literal","src":"111:2:0","typeDescriptions":{"typeIdentifier":"t_rational_42_by_1","typeString":"int_const 42"},"value":"42"},"visibility":"internal"},{"body":{"id":8,"nodeType":"Block","src":"133:2:0","statements":[]},"id":9,"implemented":true,"kind":"constructor","modifiers":[],"name":"","nameLocation":"-1:-1:-1","nodeType":"FunctionDefinition","parameters":{"id":6,"nodeType":"ParameterList","parameters":[],"src":"130:2:0"},"returnParameters":{"id":7,"nodeType":"ParameterList","parameters":[],"src":"133:0:0"},"scope":18,"src":"119:16:0","stateMutability":"nonpayable","virtual":false,"visibility":"public"},{"body":{"id":16,"nodeType":"Block","src":"188:25:0","statements":[{"expression":{"id":14,"name":"c","nodeType":"Identifier","overloadedDeclarations":[],"referencedDeclaration":5,"src":"205:1:0" [...]

2023-09-25 12:21 UTC, hedgar2017 commented
@qiaoxrcn thanks! We'll check.
Could you provide a little more context why do you need this field?

2023-09-25 12:28 UTC, hedgar2017 commented
@idea404 could you please explain step by step what is happening?

2023-09-26 01:10 UTC, qiaoxrcn commented
> @idea404 could you please explain step by step what is happening?

This is a tool being developed by unifra lab called "solidity-now".  It scans the bytecode of contracts, checks if the behavior of each bytecode is consistent with Ethereum, and provides warning messages if inconsistencies are found. This tool aims to assist contract developers in migrating contracts from Ethereum to zkSync more effectively.

Reference here: https://github.com/unifralabs/solidity-now#use-it-with-zksync-hardhat-plugins

2023-09-26 12:24 UTC, hedgar2017 commented
> > @idea404 could you please explain step by step what is happening?
> 
> This is a tool being developed by unifra lab called "solidity-now". It scans the bytecode of contracts, checks if the behavior of each bytecode is consistent with Ethereum, and provides warning messages if inconsistencies are found. This tool aims to assist contract developers in migrating contracts from Ethereum to zkSync more effectively.
> 
> Reference here: https://github.com/unifralabs/solidity-now#use-it-with-zksync-hardhat-plugins

Thanks! I'll check all these fields and make sure they are fixed by the next release.

2023-10-09 03:28 UTC, qiaoxrcn commented
> Fixed in zksolc v1.3.15. Please update!

```
~/GitHub/matter-labs/zksolc-bin/macosx-amd64/zksolc-macosx-amd64-v1.3.15 --standard-json   --solc ~/Library/Caches/hardhat-nodejs/compilers-v2/macosx-amd64/solc-macosx-amd64-v0.8.17+commit.8df45f5f < ./input.json> out.json
```
`legacyAssembly` is null.  Did I use this command correctly?
input.json content is:
```
{
  "language": "Solidity",
  "sources": {
    "@matterlabs/zksync-contracts/l2/system-contracts/BootloaderUtilities.sol": {
      "content": "// SPDX-License-Identifier: MIT\n\npragma solidity ^0.8.0;\n\nimport \"./interfaces/IBootloaderUtilities.sol\";\nimport \"./libraries/TransactionHelper.sol\";\nimport \"./libraries/RLPEncoder.sol\";\nimport \"./libraries/EfficientCall.sol\";\n\n/**\n * @author Matter Labs\n * @notice A contract that provides some utility methods for the bootloader\n * that is very hard to write in Yul.\n */\ncontract BootloaderUtilities is IBootloaderUtilities {\n    using TransactionHelper for *;\n\n    /// @notice Calculates the canonical transaction hash and the recommended transaction hash.\n    /// @param _transaction The transaction.\n    /// @return txHash and signedTxHash of the transaction, i.e. the transaction hash to be used in the explorer and commits to all\n    /// the fields of the transaction and the recommended hash to be signed for this transaction.\n    /// @dev txHash must be unique for all transactions.\n    function getTransactionHashes(\n        Transaction calldata _transaction\n    ) external view override returns (bytes32 txHash, bytes32 signedTxHash) {\n        signedTxHash = _transaction.encodeHash();\n        if (_transaction.txType == EIP_712_TX_TYPE) {\n            txHash = keccak256(bytes.concat(signedTxHash, EfficientCall.keccak(_transaction.signature)));\n        } else if (_transaction.txType == LEGACY_TX_TYPE) {\n            txHash = encodeLegacyTransactionHash(_transaction);\n        } else if (_transaction.txType == EIP_1559_TX_TYPE) {\n            txHash = encodeEIP1559TransactionHash(_transaction);\n        } else if (_transaction.txType == EIP_2930_TX_TYPE) {\n            txHash = encodeEIP2930TransactionHash(_transaction);\n        } else {\n            revert(\"Unsupported tx type\");\n        }\n    }\n\n    /// @notice Calculates the hash for a legacy transaction.\n    /// @param _transaction The legacy transaction.\n    /// @return txHash The hash of the transaction.\n    function encodeLegacyTransactionHash(Transaction calldata _transaction) internal view returns (bytes32 txHash) {\n        // Hash of legacy transactions are encoded as one of the:\n        // - RLP(nonce, gasPrice, gasLimit, to, value, data, chainId, 0, 0)\n        // - RLP(nonce, gasPrice, gasLimit, to, value, data)\n        //\n        // In this RLP encoding, only the first one above list appears, so we encode each element\n        // inside list and then concatenate the length of all elements with them.\n\n        bytes memory encodedNonce = RLPEncoder.encodeUint256(_transaction.nonce);\n        // Encode `gasPrice` and `gasLimit` together to prevent \"stack too deep error\".\n        bytes memory encodedGasParam;\n        {\n            bytes memory encodedGasPrice = RLPEncoder.encodeUint256(_transaction.maxFeePerGas);\n            bytes memory encodedGasLimit = RLPEncoder.encodeUint256(_transaction.gasLimit);\n            encodedGasParam = bytes.concat(encodedGasPrice, encodedGasLimit);\n        }\n\n        bytes memory encodedTo = RLPEncoder.encodeAddress(address(uint160(_transaction.to)));\n        bytes memory encodedValue = RLPEncoder.encodeUint256(_transaction.value);\n        // Encode only the length of the transaction data, and not the data itself,\n        // so as not to copy to memory a potentially huge transaction data twice.\n        bytes memory encodedDataLength;\n        {\n            // Safe cast, because the length of the transaction data can't be so large.\n            uint64 txDataLen = uint64(_transaction.data.length);\n            if (txDataLen != 1) {\n                // If the length is not equal to one, then only using the length can it be encoded definitely.\n                encodedDataLength = RLPEncoder.encodeNonSingleBytesLen(txDataLen);\n            } else if (_transaction.data[0] >= 0x80) {\n                // If input is a byte in [0x80, 0xff] range, RLP encoding will concatenates 0x81 with the byte.\n                encodedDataLength = hex\"81\";\n            }\n            // Otherwise the length is not encoded at all.\n        }\n\n        bytes memory rEncoded;\n        {\n            uint256 rInt = uint256(bytes32(_transaction.signature[0:32]));\n            rEncoded = RLPEncoder.encodeUint256(rInt);\n        }\n        bytes memory sEncoded;\n        {\n            uint256 sInt = uint256(bytes32(_transaction.signature[32:64]));\n            sEncoded = RLPEncoder.encodeUint256(sInt);\n        }\n        bytes memory vEncoded;\n        {\n            uint256 vInt = uint256(uint8(_transaction.signature[64]));\n            require(vInt == 27 || vInt == 28, \"Invalid v value\");\n\n            // If the `chainId` is specified in the transaction, then the `v` value is encoded as\n            // `35 + y + 2 * chainId == vInt + 8 + 2 * chainId`, where y - parity bit (see EIP-155).\n            if (_transaction.reserved[0] != 0) {\n                vInt += 8 + block.chainid * 2;\n            }\n\n            vEncoded = RLPEncoder.encodeUint256(vInt);\n        }\n\n        bytes memory encodedListLength;\n       { unchecked {\n            uint256 listLength = encodedNonce.length +\n                encodedGasParam.length +\n                encodedTo.length +\n                encodedValue.length +\n                encodedDataLength.length +\n                _transaction.data.length +\n                rEncoded.length +\n                sEncoded.length +\n                vEncoded.length;\n\n            // Safe cast, because the length of the list can't be so large.\n            encodedListLength = RLPEncoder.encodeListLen(uint64(listLength));\n        }}\n\n        return\n            keccak256(\n                bytes.concat(\n                    encodedListLength,\n                    encodedNonce,\n                    encodedGasParam,\n                    encodedTo,\n                    encodedValue,\n                    encodedDataLength,\n                    _transaction.data,\n                    vEncoded,\n                    rEncoded,\n                    sEncoded\n                )\n            );\n    }\n\n    /// @notice Calculates the hash for an EIP2930 transaction.\n    /// @param _transaction The EIP2930 transaction.\n    /// @return txHash The hash of the transaction.\n    function encodeEIP2930TransactionHash(Transaction calldata _transaction) internal view returns (bytes32) {\n        // Encode all fixed-length params to avoid \"stack too deep error\"\n        bytes memory encodedFixedLengthParams;\n        {\n            bytes memory encodedChainId = RLPEncoder.encodeUint256(block.chainid);\n            bytes memory encodedNonce = RLPEncoder.encodeUint256(_transaction.nonce);\n            bytes memory encodedGasPrice = RLPEncoder.encodeUint256(_transaction.maxFeePerGas);\n            bytes memory encodedGasLimit = RLPEncoder.encodeUint256(_transaction.gasLimit);\n            bytes memory encodedTo = RLPEncoder.encodeAddress(address(uint160(_transaction.to)));\n            bytes memory encodedValue = RLPEncoder.encodeUint256(_transaction.value);\n            encodedFixedLengthParams = bytes.concat(\n                encodedChainId,\n                encodedNonce,\n                encodedGasPrice,\n                encodedGasLimit,\n                encodedTo,\n                encodedValue\n            );\n        }\n\n        // Encode only the length of the transaction data, and not the data itself,\n        // so as not to copy to memory a potentially huge transaction data twice.\n        bytes memory encodedDat [...]

2023-10-09 15:18 UTC, hedgar2017 commented
@qiaoxrcn I've checked your input.
Apparently, `solc` has produced compile-time errors.
That's why you don't see any output apart from AST.

2023-10-11 02:15 UTC, qiaoxrcn commented
> @qiaoxrcn I've checked your input. Apparently, `solc` has produced compile-time errors. That's why you don't see any output apart from AST.
> 
> You've reached the EVM stack limit of 16 slots, so by no means you can get an EVMLA representation for that.

Thanks! 
```
CompilerError: Stack too deep. Try compiling with `--via-ir` (cli) or the equivalent `viaIR: true` (standard JSON) while enabling the optimizer. Otherwise, try removing local variables.
   --> @matterlabs/zksync-contracts/l2/system-contracts/BootloaderUtilities.sol:104:34:
    |
104 |             uint256 listLength = encodedNonce.length +
    |                                  ^^^^^^^^^^^^


Error HH600: Compilation failed

For more info go to https://hardhat.org/HH600 or run Hardhat with --show-stack-traces
```

2023-10-11 11:33 UTC, hedgar2017 commented
> generated by zksolc:
> 
> ```
> evm":{
> "legacyAssembly":{
>   ".auxdata":null,".code":[
>   {"name":"PUSH","value":"80"},
>   {"name":"PUSH","value":"40"}
> ...
> ```
> 
> generated by solc:
> 
> ```
> {".code":
> [
> {"begin":62,"end":378,"name":"PUSH","source":0,"value":"80"},
> ...
> ```
> 
> Why missing fileds `begin`,`end`,`source`?

Just to save space as we have never used them. Is it crucial?

2023-10-11 16:09 UTC, qiaoxrcn commented
> Just to save space as we have never used them. Is it crucial?

Ha, they are important to `solidity-now`. May I request to put these fields back?

2023-10-11 18:33 UTC, hedgar2017 commented
> > Just to save space as we have never used them. Is it crucial?
> 
> 
> 
> Ha, they are important to `solidity-now`. May I request to put these fields back?

Sure.
But you can use solc to get this output for now, correct?

2023-10-12 00:12 UTC, qiaoxrcn commented
> > > Just to save space as we have never used them. Is it crucial?
> > 
> > 
> > Ha, they are important to `solidity-now`. May I request to put these fields back?
> 
> Sure. But you can use solc to get this output for now, correct?

Yes,  output generated by zksolc v1.3.15 contains `evm.legacyAssembly` now. 
Additionally, there is another issue unrelated to this pull request. The contract you just mentioned, which reached the EVM stack limit of 16 slots, comes from official system contracts.
`@matterlabs/zksync-contracts/l2/system-contracts/BootloaderUtilities.sol:104:34` .
Should we fix this contract?

2023-10-12 12:49 UTC, hedgar2017 commented
> > > > Just to save space as we have never used them. Is it crucial?
> 
> > > 
> 
> > > 
> 
> > > Ha, they are important to `solidity-now`. May I request to put these fields back?
> 
> > 
> 
> > Sure. But you can use solc to get this output for now, correct?
> 
> 
> 
> Yes,  output generated by zksolc v1.3.15 contains `evm.legacyAssembly` now. 
> 
> Additionally, there is another issue unrelated to this pull request. The contract you just mentioned, which reached the EVM stack limit of 16 slots, comes from official system contracts.
> 
> `@matterlabs/zksync-contracts/l2/system-contracts/BootloaderUtilities.sol:104:34` .
> 
> Should we fix this contract?

No, system contracts are only supposed to be compiled by zksolc via Yul. Not any other way.

2023-10-13 07:36 UTC, qiaoxrcn commented
> > > > > Just to save space as we have never used them. Is it crucial?
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > Ha, they are important to `solidity-now`. May I request to put these fields back?
> > 
> > 
> > > 
> > 
> > 
> > > Sure. But you can use solc to get this output for now, correct?
> > 
> > 
> > Yes,  output generated by zksolc v1.3.15 contains `evm.legacyAssembly` now.
> > Additionally, there is another issue unrelated to this pull request. The contract you just mentioned, which reached the EVM stack limit of 16 slots, comes from official system contracts.
> > `@matterlabs/zksync-contracts/l2/system-contracts/BootloaderUtilities.sol:104:34` .
> > Should we fix this contract?
> 
> No, system contracts are only supposed to be compiled by zksolc via Yul. Not any other way.

Got it. Thanks a lot !

2023-10-28 17:05 UTC, hedgar2017 commented
@qiaoxrcn the fields have been added in the latest release (v1.3.16).

2023-11-03 00:37 UTC, qiaoxrcn commented
> @qiaoxrcn the fields have been added in the latest release (v1.3.16).

Thanks! It works now.

2023-11-03 00:37 UTC, closed without merging